[package]
name = "comment-away"
version = "0.1.0"
edition = "2021"
[dependencies]
clap = { version = "4.5.21", features = ["derive"] }
comment_away_lib = {path = "../lib/"}
serde = { version = "1.0.215", features = ["derive"] }
